a = str(input('Escriba sus nombres completos: '))
b = str(input('Escribas sus Apellidos completos: '))
c = str(input('Escriba su profesion: '))
d = int(input('Escriba su año de nacimiento: '))
e = int(2025-d)
print('El (La)',c,a,b,'tiene',e,'años')