a= 10
b= 4
print('la primera variables es: ',(a))
print('el signo de la operacion es: * ')
print('la segunda variables es: ',(b))
c= (a*b)
print('el resultado es: ',(c))
print(type (c))
print('la primera variables es: ',(a))
print('el signo de la operacion es: / ')
print('la segunda variables es: ',(b))
c= (a/b)
print('el resultado es: ',(c))
print(type (c))
print('la primera variables es: ',(a))
print('el signo de la operacion es: + ')
print('la segunda variables es: ',(b))
c= (a+b)
print('el resultado es: ',(c))
print(type (c))
print('la primera variables es: ',(a))
print('el signo de la operacion es: - ')
print('la segunda variables es: ',(b))
c= (a-b)
print('el resultado es: ',(c))
print(type (c))
print('la primera variables es: ',(a))
print('el signo de la operacion es: ** ')
print('la segunda variables es: ',(b))
c= (a**b)
print('el resultado es: ',(c))
print(type (c))
print('la primera variables es: ',(a))
print('el signo de la operacion es: % ')
print('la segunda variables es: ',(b))
c= (a%b)
print('el resultado es: ',(c))
print(type (c))